### ISSUE TITLE
datepicker

### ISSUE THREAD

**Issue by coppo** [italia/ita-web-toolkit#25]
Nella documentazione non c'è un esempio di inserimento di data, sia standard usa che gov uk affrontano il problema con un approccio molto conservativo:

https://www.gov.uk/service-manual/user-centred-design/resources/patterns/dates.html#calendar-controls
https://standards.usa.gov/form-controls/#date-input

Suggerite questo approccio o l'utilizzo di datepicker accessibili come:

https://hanshillen.github.io/jqtest/#goto_datepicker
http://www.oaa-accessibility.org/examplep/datepicker1/

Nel caso di utilizzo di datepicker come credete sia meglio gestire la navigazione mobile?

**Comment by coppo** [comment]
Mi sono inbattuto in questo progetto:
http://amsul.ca/pickadate.js/
sembra molto interessante

**Comment by gunzip** [comment]
segnalo una discussione correlata: https://designpatterns.hackpad.com/Dates-vpx6XlVjIbE

in ogni caso eviterei di aprire il picker al focus sull'input (impedisce di scriverci dentro),
dedicherei un trigger che stia al di fuori del campo

**Comment by gunzip** [comment]
inserito in https://github.com/italia/ita-web-toolkit/tree/v2.2
