### ISSUE TITLE
Cookiebar

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/ita-web-toolkit#33]
Non riesco a far funzionare il componente del cookiebar incluso nel webkit
Ho provato l’originale di Carl Woodhouse e ha funzionato subito.
Il mio sito è realizzato con bootstrap 4, forse ci sono delle incompatibilità di JS?
Inoltre non capisco bene la funzione del file index.js.
Grazie.

**Comment by gunzip** [comment]
è difficile senza contesto capire perché non funziona, forse ti da qualche errore js ? (com'è incluso il componente al'interno del VS progetto ?)

il file index.js che si trova all'interno dei singoli componenti in generale serve a collegare la funzionalità dinamica a un selettore (`.js-cookieBarAccept`) nel caso specifico.
