### ISSUE TITLE
Integrare icona Instagram

### ISSUE THREAD

**Issue by mbolzan** [italia/ita-web-toolkit#49]
Ciao a tutti,
potete chiarirmi quale framework o procedura (es. "fontello-like") è stata utilizzata per produrre le icone social?
in particolare volendo averne una nuova (es. Instagram) cosa si può fare?

grazie

**Comment by gunzip** [comment]
nel toolkit è stato incluso un [set di icone](https://italia.github.io/ita-web-toolkit/components/detail/icons.html) "personalizzato", prodotto nell'ambito del progetto delle linee guida, che potesse dare più "carattere" ai siti PA. 

Le LG [non prescrivono al momento l'utilizzo di questo set](http://design.italia.it/linee-guida/visual-design/iconografia/) che tuttavia, a seconda degli sviluppi e della partecipazione, potrebbe diventare un riferimento. 

L'idea è quella di allargarlo (ma non troppo) recependo i contributi: chi vuole può condividere un SVG e/o effettuare una pull request.

**Comment by mbolzan** [comment]
Ok, quindi per chi volesse si può usare un set grafico personalizzato o un icons framework esterno.

Riporto qui per chi volesse usare Font Awesome i passi necessari per usarlo nell'ambiente di sviluppo:
- lanciare nella root del progetto ita-web-toolkit, il comando `npm install font-awesome`
- verificare la corretta creazione/installazione del package nella cartella "node_modules/font-awesome"
- inserire nel file /index.css la stringa di import `@import "font-awesome";`
- poi con run build oppure run watch, il file build.css conterrà l'insieme di CSS di Font Awesome
- nei moduli o template si utilizza quindi, ad esempio `<i class="fa fa-instagram" aria-hidden="true"></i>` secondo le indicazioni standard di http://fontawesome.io/
- consiglio poi la definizione di un css simile a questo nel file index.css del proprio tema, in modo da renderle simili come layout alle icone "embedded" del ita-web-toolkit
```
.[YOUR_THEME_PREFIX] .Header-socialIcons i.fa {
  @extend .u-background-white;
  @extend .u-color-50;
  @extend .u-padding-all-xxs;
  @extend .u-borderRadius-circle;
  @extend .u-margin-left-xs;
  @extend .u-text-m;
}
```
