### ISSUE TITLE
Implementazione modal

### ISSUE THREAD

**Issue by Bedotech** [italia/ita-web-toolkit#50]
Salve,

prima di tutto grazie del lavoro che stai svolgendo @gunzip :+1: 

Volevo chiedere se era previsto in futuro implementare le [modal](http://getbootstrap.com/javascript/#modals) in stile bootstrap e affini.

Sarebbe infatti necessario per alcune applicazioni che sto sviluppando, sono anche disposto a proportelo come pull request se secondo te potrebbe rientrare nelle linee guida.

Volevo solo avere una tua opinione prima di incominciare a integrare qualcosa che non è previsto.

**Comment by gunzip** [comment]
ciao @Bedotech, puoi dettagliare "in stile bootstrap e affini" ?

al momento esiste questa implementazione per le modali
https://italia.github.io/ita-web-toolkit/components/detail/dialog.html 

include alcune [best-practice per l'accessibilità](https://frend.co/components/dialogmodal/)

lo stile può esser modificato tramite le classi di utilità (es. http://codepen.io/anon/pen/RKayBV), volendo, senza aggiunger ulteriore CSS. detto ciò, ogni pr è ben accetta :)

**Comment by Bedotech** [comment]
Grazie, l'implementazione delle Dialog è perfetta per ciò che intendevo, grazie per la risposta rapida!
