### ISSUE TITLE
Chiusura Megamenu 

### ISSUE THREAD

**Issue by AlessandroVecchi** [italia/ita-web-toolkit#57]
Ciao,
Se clicco su una voce del menu si apre il dropdown con le sottovoci.
Istintivamente mi viene da cliccare nuovamente per chiuderlo, però non funziona. Per chiudere occorre cliccare in un altro punto della pagina. Non a caso, forse, la freccetta sparisce e non viene commutata in una freccia con direzione opposta.
Io implementerei questa funzionalità sulla voce di menu.

**Comment by gunzip** [comment]
sembra ragionevole, la mettiamo nei todo (e/o chi vuole può fare una pull request :)

**Comment by AlessandroVecchi** [comment]
Stesso principio del accordion

**Comment by AlessandroVecchi** [comment]
Ho notato che invece su dispositivi touch il funzionamento è diverso: clicco su un menu, si apre, clicco su quello a fianco, invece di aprire il corrispondente menu, come avviene da desktop, chiude il precedente. Obbliga quindi ad un click in più

**Comment by gunzip** [comment]
vero. potremmo ipotizzare di avere un handler separato per l'apertura, il che torna utile *se* i top link non sono semplici placeholder, ma veri link (es. http://www.regione.lombardia.it/wps/portal/istituzionale/HP)
fa il paio con la #52

**Comment by AlessandroVecchi** [comment]
Infatti io ho provato a mettere il link a posto del `#` ma giustamente cliccando va alla pagina.
Quindi come alternativa ho inserito il link della voce principale nel menu in questo modo

![immagine](https://cloud.githubusercontent.com/assets/20642463/23301322/a27d189c-fa89-11e6-88ff-003ffa5ba270.png)

**Comment by gunzip** [comment]
corretto nel branch v2.2
