### ISSUE TITLE
installazione 

### ISSUE THREAD

**Issue by sabongiovanni** [italia/ita-web-toolkit#66]
Salve, vorrei sapere come installare ita web toolkit, quali sono le caratteristiche del hosting che tipo di db è necessario e se è possibile integrarlo all'interno di qualche cms tipo wordpress . saluti e grazie e scusate

**Comment by gunzip** [comment]
la documentazione è disponibile qui: https://italia.github.io/ita-web-toolkit/

il toolkit si compone di HTML/JS/CSS e non realizza un backend, è pensato come ambiente di sviluppo da utilizzare sulla propria workstation. è possibile utilizzarlo per realizzare temi per i CMS più diffusi includendo i necessari JS/CSS e utilizzando gli snippet HTML di esempio.

per quanto riguarda la promozione di progetti open source (es. temi wordpress. drupal, joomla) stiamo organizzando una sezione apposita e ci saranno presto novità.

**Comment by gunzip** [comment]
@oviecch puoi elaborare una serie di domande / punti da chiarire in modo
