### ISSUE TITLE
Integrazione AngularJs

### ISSUE THREAD

**Issue by paulodiff** [italia/ita-web-toolkit#68]
Buongiorno a tutti, volevo sapere se qualcuno ha già tentato l'integrazione del toolkit con il framework AngularJs. Saluti.

**Comment by Bedotech** [comment]
Cosa intendi con integrazione? Di default angular non ha CSS di conseguenza puoi utilizzarlo come preferisci, chiaramente tutti i componenti javascript (ad esempio le dialog) non sono integrati e c'è poco da fare.

Comunque sia lo utilizzo implementando le parti in javascript dove necessario.

**Comment by paulodiff** [comment]
Volevo solo sapere se qualcuno aveva avuto esperienza in merito, ma posso confermare che l'integrazione con AngularJs è possibile, Devo come hai detto tu sistemare le dialogs e qualche altro controllo.
Grazie.
