### ISSUE TITLE
configurazione locale del template comuni

### ISSUE THREAD

**Issue by oviecch** [italia/ita-web-toolkit#69]
salve, potresti darmi istruzioni sulla configurazione locale del template comuni al posto di quello di default in http://localhost:1310/

**Comment by mbolzan** [comment]
sono qualche mese che sto lavorando col web-toolkit e avendo già affrontato diverse situazioni, cerco di tenere "vive" queste richieste di Help per chi è alle prime armi :-)

a questo indirizzo https://italia.github.io/ita-web-toolkit/ trovate il toolkit, diciamo "running", quindi navigabile allo stato attuale per quanto riguarda gli sviluppi e con l'introduzione e la documentazione.

far girare il toolkit in locale è solo un passo aggiuntivo, seppur al 99% da farsi, per chi deve sviluppare un proprio tema, un componente ecc (eventualmente qualcosa è già stato scritto in altri issues, ma se serve ne riparliamo anche qui)

nel merito della domanda #69 di @oviecch 
sotto i Templates ci sono semplicemente delle sottocartelle specifiche, tra i quali :
- i Layout (=pezzi più grossi di layout che comprendo più elementi, ad esempio la Gallery è un insieme di Card, le News è una particolare Grid)
- poi ci sono le Page (=vere e proprie pagine complete di header, footer e contenuti, che richiamano pezzi di pagina, layout specifici e componenti, ad esempio la pagina Landing renderizza il layout-landing)

la cartella Comuni contiene solo una variante delle pagine "Default" e "Megamenu", principalmente per far vedere come un Comune dovrebbe declinare la tassonomia delle pagine e dei servizi, quindi tali pagine aggiungono "semantica" al modello base.

il concetto generale è sempre : 
a) prendere css e js compilato dal toolkit e introdurlo as-is nell'ambiente di "costruzione" del sito (che sia un CMS o un sito statico o dinamico)
b) prendere (copy/paste) l'html dal toolkit, solo quello che ovviamente ci serve, e metterlo nell'ambiente di "costruzione" del sito

spero di essere stato utile, oltre che logorroico :)

**Comment by oviecch** [comment]
ho installato il webtoolkit in locale, come posso interfacciarlo con drupal o wordpress per la gestione dei contenuti?

**Comment by oviecch** [comment]
quindi in base a quello che mi dici come potrei inserire il megamenu in wordpress?

**Comment by mbolzan** [comment]
cerco di descrivere meglio il concetto generale di **"sviluppo di un sito partendo dal toolkit"**:

1) da un parte c'è il toolkit con cui si sviluppa una guida di stile, cioè un oggetto di visual design con cui si indica come appariranno i vari pezzi del mio sito; tramite il comando di _npm run build_ si generano fondamentalmente i file css e js e si genera la styleguide stessa. NOn si genera nessun tipo di sito navigabile o usabile così com'è (e non si possono generare "oggetti" usabili in nessun tipo di cms).

2) dall'altra parte c'è quello che io definisco "sito in costruzione", può essere un sito statico oppure un sito dinamico, esempio wordpress o drupal o qualsiasi altra cosa in qualsiasi altro linguaggio web; (questo sito in costruzione lo dovete costruire voi, non lo fa il toolkit!)

le due fasi sono completamente distinte, prima lavoro col toolkit e genero la guida di stile, decidendo per esempio di che colore sarà il mio sito, e genero i file css e js minificati tramite la build del toolkit.

Poi se voglio fare un sito "in costruzione" con wordpress devo costruire un tema apposta dentro a wordpress (esula dallo scopo di questo progetto, spiegare come si crea un Tema in Wp) nel quale devo incollare così come sono i file css/js e costruire nei vari file php del Tema i pezzi dell'html che ho a disposizione nella guida di stile).

nel issue #66 si è scritto che potrebbe partire una sezione dedicata alla promozione di progetti open source, come lo sviluppo di temi wordpress. Attualmente non abbiamo ulteriori riferimenti in merito.

**Comment by gunzip** [comment]
grazie@mbolzan :)

migliorare la documentazione è sicuramente tra le priorità.
