### ISSUE TITLE
template Megamenu

### ISSUE THREAD

**Issue by oviecch** [italia/ita-web-toolkit#70]
potreste darmi istruzioni sulla configurazione locale del template comuni Megamenù al posto di quello di default in http://localhost:1310/

**Comment by mbolzan** [comment]
@oviecch fai riferimento agli issue #69 e #73 dove indico qualche Help su installazione e sviluppo.

Senza voler fare nessuna polemica ovviamente :) ma aprire diversi issue con richieste simili e poco dettagliate come questo, non è esattamente lo scopo di tale strumento su github, che è invece orientato a raccogliere problematiche specifiche sul progetto e bug da risolvere sul codice.
