### ISSUE TITLE
Fallimento build e creazione index.css

### ISSUE THREAD

**Issue by stefanorg** [italia/ita-web-toolkit#76]
Ciao,

Sto provando a fare il build del toolkit, la build fallisce eseguento il comando `npm run build:css`

Ottendo il seguente errore:

```
$ suitcss -m -c .postcss.js index.css build/build.css 

index.css
7:1     ⚠  Cannot find module 'src/utils/**/index.css' from '/home/stefano/lavoro/ita-web-toolkit' [postcss-import]
11:1    ⚠  Cannot find module 'src/components/**/index.css' from '/home/stefano/lavoro/ita-web-toolkit' [postcss-import]
13:1    ⚠  Cannot find module 'src/modules/**/index.css' from '/home/stefano/lavoro/ita-web-toolkit' [postcss-import]
15:1    ⚠  Cannot find module 'src/extra/**/index.css' from '/home/stefano/lavoro/ita-web-toolkit' [postcss-import]

Done in 2.39s.

```

In questo modo anche provando a fare `npm run watch` e collegandomi a `localhost:1310` il risultato è un insieme di scritte senza stile.

Come posso risolvere?

**Comment by forlanim** [comment]
hai controllato che i file ci siano e che i permessi siano corretti?

**Comment by stefanorg** [comment]
ciao @forlanim,

in pratica ho utilizzato `yarn` per l'installazione delle dipendenze e sicuramente è stato quello il problema, perchè provando con `npm install` il tutto ha funzionato senza problemi.
