### ISSUE TITLE
Form-field--withPlaceholder

### ISSUE THREAD

**Issue by jsb81** [italia/ita-web-toolkit#78]
Sto cercando di creare delle form con la label impostata come placeholder nelle input fields. 
Il problema è che questa viene visualizzata solamente se l'input field viene impostata come required. Questo perché è impostata la seguente regola nel css:

`.Form-field--withPlaceholder .Form-input:focus + .Form-label,
.Form-field--withPlaceholder .Form-input:valid + .Form-label {
  opacity: 0;
}`

Qualcuno ha trovato una soluzione a questo "problema"?

Grazie.

**Comment by gunzip** [comment]
la regola serve a evitare che la label venga mostrata sovrapposta al valore del testo immesso nel campo di input quando questo perde il focus: https://css-tricks.com/float-labels-css/#article-header-id-3

in sostanza, si può anche levare l'attributo required, dopodiché è necessario introdurre del javascript per nascondere la label quando il campo di input è valorizzato

**Comment by jsb81** [comment]
Ok risolvo con un js. Grazie
