### ISSUE TITLE
Utils css non interpretati

### ISSUE THREAD

**Issue by ilCleme** [italia/ita-web-toolkit#79]
Buongiorno a tutti,
ho scaricato, installato e buildato l'ultima release del toolkit, senza nessun problema.

In seguito ho aggiunto un modulo che si compone di un file per il template e di un file css denominato index.css, ho aggiunto la regola di import nel file index.css che si trova nella root, ho fatto partire la build ma tutta la cartella "utils" e i relativi "sottomoduli" non vengono interpretati correttamente.

In questo modo quando vado ad eseguire il watch del toolkit mi ritrovo con delle pagine HTML a cui mancano parecchi stili.

I comandi per il "build" o per la "watch" li ho lanciati sia da WebStorm che direttamente da Terminale ma non cambia nulla.

La macchina su cui sto lavorando è una macchina con Windows 7.
La versione di node.js è l'ultima stabile, v6.10.3.

Ho provato a reinstallare le dipendenze npm ma non cambia nulla. 
Da cosa può dipendere?

**Comment by gunzip** [comment]
ciao mattia, qualche domanda per inquadrare il problema:
che intendi esattamente con 'non vengono interpretati correttamente'  ?
ci sono messagi di errore in console ?
hai installato altri pacchetti tramite npm ?

puoi controllare di avere la versione 2.0 di postcss-easy-import:

```
$ npm ls | grep import
├─┬ postcss-easy-import@2.0.0
│ ├─┬ postcss-easy-import@2.0.0
│ │ └── postcss-import@9.1.0
```

**Comment by ilCleme** [comment]
Ciao Danilo, grazie per la risposta intanto.
Si, ho la versione 2.0 di postcss-easy-import.
Ho degli errori in console, che sono i seguenti (ho lanciato solo la build dei css in questo caso, ma anche se lancio `npm run build` sono gli unici a comparire):

```
npm run build:css
7:1	‼  Cannot find module src/utils/**/index.css from ... [postcss-import]
11:1	‼  Cannot find module src/components/**/index.css from ... [postcss-import]
13:1	‼  Cannot find module src/modules/**/index.css from ... [postcss-import]
15:1	‼  Cannot find module src/extra/**/index.css from ... [postcss-import]
Process finished with exit code 0
```

Ho installato i seguenti pacchetti npm che sono stati installati senza alcun problema:
> "magnific-popup": "^1.1.0",
> "fr-tabs": "^1.0.5"

Magnific popup non è ancora attivo (o meglio non ci sono script che ne fanno uso, è solo importato)
Ed ho un semplice script js che attiva dei tabs usando il pacchetto fr-tabs.

```
import Frtabs from 'fr-tabs'

/* eslint-enable */

const tabs = Frtabs({
    // String - Outer container selector, hook for JS init() method
    selector: '.js-fr-tabs',
    // String - List selector to transform into tablist
    tablistSelector: '.js-fr-tabs__tablist',
    // String - Containers which hold content, toggled via tabs
    tabpanelSelector: '.js-fr-tabs__panel',
    // String - Class name that will be added to the selector when the component has been initialised
    tabsReadyClass: 'fr-tabs--is-ready'
})

export default { tabs, Frtabs }
```
La versione di npm che ho sul sistema è 3.10.5.
I permessi delle cartelle sono così settati nella directory 'utils':
```
total 7
drwxr-xr-x    1 Daniele  Administ        0 May 16 09:48 borders
drwxr-xr-x    1 Daniele  Administ        0 May 16 09:48 colors
drwxr-xr-x    1 Daniele  Administ        0 May 16 09:48 corners
drwxr-xr-x    1 Daniele  Administ     4096 May 16 09:48 display
drwxr-xr-x    1 Daniele  Administ        0 May 16 09:48 layout
drwxr-xr-x    1 Daniele  Administ        0 May 16 09:48 shadows
drwxr-xr-x    1 Daniele  Administ     4096 May 16 09:48 space
drwxr-xr-x    1 Daniele  Administ     4096 May 16 09:48 text
-rw-r--r--    1 Daniele  Administ       36 May 16 09:48 utils.config.js
drwxr-xr-x    1 Daniele  Administ        0 May 16 09:48 zindex
```
Che possa essere un problema di permessi?

**Comment by gunzip** [comment]
probabilmente installando i nuovi pacchetti npm ti ha sovrascritto postcss-easy-import, puoi verificarlo

**Comment by ilCleme** [comment]
Danilo, il contenuto del CHANGELOG.md di postcss-easy-import è il seguente:
```
# Changelog

## 1.0.1

- Fix `package.json` files filter

## 1.0.0

Initial release
```

Devo provare a lanciare un `npm install suitcss-preprocessor`?

**Comment by gunzip** [comment]
come "fix" occorre tornare alla v2.0 di postcss-easy-import che usa suitcss-proprocessor (facile a dirsi, difficile a farsi perché implica manipolare il file npm-shrinkwrap.json e rilanciare npm install)

alternativamente (più facile da attuare nonché consigliato), è possibile usare una versione più aggiornata del TK che non presenta il problema:

https://github.com/italia/ita-web-toolkit/tree/v2.2

è una "release candidate" per una 1.0.

**Comment by ilCleme** [comment]
Danilo è corretto il procedimento che mi hai consigliato, ho fatto rebase del mio ramo dev sul ramo v2.2, dopo le dovute merge il comando di build risponde correttamente.

É quindi consigliato usare il ramo v2.2 per un utilizzo più sicuro del toolkit? E per poter inserire ulteriori dipendenze senza intaccare quelle già attualmente presenti?

**Comment by gunzip** [comment]
si è consigliato il 2.2 per chi inizia adesso. 
il problema delle nuove dip. si presenta solo con il master (che usa npm-shrinkwrap.json),
dovrebbe essere risolto nella 2.2 (eventualmente, puoi confermarlo ?)

**Comment by ilCleme** [comment]
Ho fatto alcune prove, ed effettivamente la build a partire dal ramo v2.2 termina sempre e senza errori.

Ho aggiunto al progetto queste dipendenze:

> magnific-popup
> fr-tabs

Dopo l'aggiunta con `npm install <nome-dipendenza> --save` ho lanciato la build ed è sempre terminata correttamente.

È presente solo un warning [stylelint] su zindex/index.css; 
Il resto funziona tutto.

Grazie mille @gunzip per il supporto.

**Comment by gunzip** [comment]
grazie a te per il feedback, chiudo la issue :)
