### ISSUE TITLE
Installazione del repository

### ISSUE THREAD

**Issue by lodolini** [italia/ita-web-toolkit#81]
Ho difficoltà nell'installare il repository. Ho creato un account, ho verificato l'account per mezzo della email cje mi è giunta, ho eseguito le riche di comando suggerite, ma scaturisce sempre lo stesso messaggio di accesso negato. Non so cosa fare. Grazie.

**Comment by gunzip** [comment]
ciao @lodolini. non ho suffienti informazioni per poter fornire supporto. con 'account' intendi un account su GitHub ? a quale messaggio di accesso negato ti riferisci esattamente ?
