### ISSUE TITLE
Download CSS e JS già compilati

### ISSUE THREAD

**Issue by erikpassadore** [italia/ita-web-toolkit#87]
Buongiorno,
mi sono accorto che non funziona più il seguente link per scaricare i CSS e i JS già compilati utili per la creazione di un sito web seguendo le linee guida.
https://github.com/italia/ita-web-toolkit/tree/gh-pages/build

Il linkl'ho recuperato da questa pagina https://italia.github.io/ita-web-toolkit/docs/come-iniziare.
E' possibile accedere in qualche modo all'ultima versione di questi file?

Grazie

**Comment by gunzip** [comment]
grazie per la segnalazione, il link corretto è

https://github.com/italia/ita-web-toolkit/tree/gh-pages/ita-web-toolkit/build

lo aggiorniamo nei docs.

**Comment by erikpassadore** [comment]
Grazie mille per la celere risposta.
Come posso essere "avvisato" quando uno di questi componenti viene aggiornato?

**Comment by gunzip** [comment]
le modifiche ai componenti vengono indicate nel CHANGELOG:
https://github.com/italia/ita-web-toolkit/blob/master/CHANGELOG.md

puoi rimanere aggiornato, per ogni cambiamento, tramite la funzione 'watch' di github

**Comment by erikpassadore** [comment]
Ottimo. Grazie mille
