### ISSUE TITLE
Tanti link errati? Nella pagina "Come iniziare"

### ISSUE THREAD

**Issue by ccontavalli** [italia/ita-web-toolkit#88]
Nella pagina:
https://italia.github.io/ita-web-toolkit/docs/come-iniziare.html

C'è scritto:
"Puoi scaricare i file CSS / JS già compilati da incorporare in ogni pagina:
CSS / Javascript già compilati"

Il link "CSS / Javascript già compilati" punta a:
https://github.com/italia/ita-web-toolkit/tree/gh-pages/build

che è una directory vuota? un symlink che punta a se stesso? In ogni modo, non c'è il materiale indicato.

Si dovrebbe o aggiornare il repository per contere i file giusti in build/, oppure cambiare il link nelle pagine.

**Comment by ccontavalli** [comment]
Anche i link: "facendo riferimento al template generico di esempio" portano a 404?

**Comment by gunzip** [comment]
grazie @ccontavalli, ho corretto i link
