### ISSUE TITLE
RIchiesta di supporto: installazione

### ISSUE THREAD

**Issue by whiteseraph83** [italia/ita-web-toolkit#94]
Buongiorno, scusate il disturbo.
Ho seguito le istruzioni nella pagina "Come iniziare" https://italia.github.io/ita-web-toolkit/docs/come-iniziare.html
Ho prelevato da github la cartella build, contenente una build funzionante con tutti i componenti js e css già compilati.
Nel file index.html ho sostituito il percorso alla riga:
<script>__PUBLIC_PATH__ = '/assets/javascript/'</script>
con la mia path ma l'unica cosa che vedo quando apro l' index.html da browser è:  "{{ yield|safe }}"

Potete aiutarmi?
grazie in anticipo

**Comment by gunzip** [comment]
ciao @whiteseraph83. non mi è chiaro qual è il risultato atteso. l'index.html di esempio è un file 'vuoto', il cui scopo è mostrare come vanno inclusi i javascript / CSS all'interno delle pagine / template. al posto della direttiva `{{ yield|safe }}` è previsto che vengano inseriti i contenuti effettivi della pagina. puoi darmi altri elementi per poterti supportare ?
