### ISSUE TITLE
Richiesta supporto

### ISSUE THREAD

**Issue by iPako** [italia/ita-web-toolkit#99]
Buonasera, 
ho scaricato e installato, secondo la guida, tutti files necessari al corretto funzionamento delle componenti a disposizione, tuttavia queste non funzionano. Mi riferisco in particolare alle due che ho provato, MegaMenu e TreeView.
Specifico che nel sito utilizzo la versione di angular 1.6.4 e le componenti (header, corpo centrale e footer) vengono incluse all'interno della pagina principale (dove carico tutti js e css necessari) attraverso la direttiva ng-include.

**Comment by gunzip** [comment]
ciao @iPako , le informazioni fornite non permettono di capire l'origine del mafunzionamento, hai una pagina di esempio da condividere ?

**Comment by iPako** [comment]
ciao @gunzip e grazie della risposta.
Credo di aver risolto ma chiedo comunque conferma: da quello che ho capito il file iwt.js deve essere letto DOPO che la pagina è stata scritta in quanto questo script associa delle funzioni js in base ai nomi delle classi css presenti nella pagina (giusto?); il problema è che la direttiva angular `ng-include`, carica i pezzi di html inclusi, dopo aver scritto la pagina principale e quindi dopo aver caricato il js, di conseguenza non vengono associate le function ai componenti e il risultato è che sebbene lo stile venga ripreso correttamente, gli script semplicemente, non funzionano.
La soluzione che ho adottato è stata quella di far caricare lo script direttamente da angular dopo aver caricato le varie componenti html incluse, attraverso una direttiva custom 
`<script type="text/javascript-lazy" src="assets/js/IWT.min.js"></script>`

**Comment by gunzip** [comment]
confermo che la soluzione adottata è corretta.
